/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import datos.AlumnosJDBC;
import domain.Alumnos;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

public class FvisualizacionBD extends javax.swing.JFrame {

    private Alumnos al1 = new Alumnos();
    private AlumnosJDBC lista_alumnos = new AlumnosJDBC();

    private DefaultTableModel modelo;
    private TableRowSorter buscador;
    Object o[] = null;
    List<Alumnos> arr1 = lista_alumnos.select();

    public FvisualizacionBD() {
        super("Registro de Alumnos");
        
        initComponents();

        modelo = (DefaultTableModel) jTable2.getModel();

        for (int i = 0; i < arr1.size(); i++) {
            modelo.addRow(o);
            jTable2.setValueAt(arr1.get(i).getMarca_Temporal(), i, 0);
            jTable2.setValueAt(arr1.get(i).getDNI(), i, 1);
            jTable2.setValueAt(arr1.get(i).getApellido(), i, 2);
            jTable2.setValueAt(arr1.get(i).getNombre(), i, 3);
            jTable2.setValueAt(arr1.get(i).getFecha_N(), i, 4);
            jTable2.setValueAt(arr1.get(i).getEdad(), i, 5);
            jTable2.setValueAt(arr1.get(i).getDireccion(), i, 6);
            jTable2.setValueAt(arr1.get(i).getPiso_Depto(), i, 7);
            jTable2.setValueAt(arr1.get(i).getLocalidad(), i, 8);
            jTable2.setValueAt(arr1.get(i).getCorreo(), i, 9);
            jTable2.setValueAt(arr1.get(i).getCelular(), i, 10);
            jTable2.setValueAt(arr1.get(i).getCurso(), i, 11);
            jTable2.setValueAt(arr1.get(i).getDivision(), i, 12);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filtroAños = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca Temporal", "DNI", "Apellido", "Nombres", "Fecha de Nacimiento", "Edad", "Direccion", "Piso", "Localidad", "Correo", "Celular", "Curso", "Division"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
            jTable2.getColumnModel().getColumn(6).setResizable(false);
            jTable2.getColumnModel().getColumn(7).setResizable(false);
            jTable2.getColumnModel().getColumn(8).setResizable(false);
            jTable2.getColumnModel().getColumn(9).setResizable(false);
            jTable2.getColumnModel().getColumn(10).setResizable(false);
            jTable2.getColumnModel().getColumn(12).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Base de Datos de Alumnos");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Apellido");

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        filtroAños.add(jRadioButton1);
        jRadioButton1.setText("1er Año");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        filtroAños.add(jRadioButton2);
        jRadioButton2.setText("2do Año");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        filtroAños.add(jRadioButton3);
        jRadioButton3.setText("3er Año");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        filtroAños.add(jRadioButton4);
        jRadioButton4.setText("4to Año");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        filtroAños.add(jRadioButton5);
        jRadioButton5.setText("5to Año");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        filtroAños.add(jRadioButton6);
        jRadioButton6.setText("6to Año");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Filtro Por Años");

        filtroAños.add(jRadioButton7);
        jRadioButton7.setSelected(true);
        jRadioButton7.setText("Todos Los Años");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jMenu1.setText("Inicio");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sistema");

        jMenu4.setText("Alumnos");

        jMenuItem1.setText("Visualizar Base De Datos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem8.setText("Agregar Alumnos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem2.setText("Editar Base de Datos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Dar de Baja");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenu2.add(jMenu4);

        jMenu5.setText("Padres y Tutores");

        jMenuItem5.setText("Visualizar Base de Datos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem9.setText("Agregar Padres/Tutores");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuItem6.setText("Editar Base de Datos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem7.setText("Dar de Baja");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem10.setText("Acerca de");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Manual de Usuario");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(Reset))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed

        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();
        for (int i = 0; i < arr1.size(); i++) {
            modelo.addRow(o);
            jTable2.setValueAt(arr1.get(i).getMarca_Temporal(), i, 0);
            jTable2.setValueAt(arr1.get(i).getDNI(), i, 1);
            jTable2.setValueAt(arr1.get(i).getApellido(), i, 2);
            jTable2.setValueAt(arr1.get(i).getNombre(), i, 3);
            jTable2.setValueAt(arr1.get(i).getFecha_N(), i, 4);
            jTable2.setValueAt(arr1.get(i).getEdad(), i, 5);
            jTable2.setValueAt(arr1.get(i).getDireccion(), i, 6);
            jTable2.setValueAt(arr1.get(i).getPiso_Depto(), i, 7);
            jTable2.setValueAt(arr1.get(i).getLocalidad(), i, 8);
            jTable2.setValueAt(arr1.get(i).getCorreo(), i, 9);
            jTable2.setValueAt(arr1.get(i).getCelular(), i, 10);
            jTable2.setValueAt(arr1.get(i).getCurso(), i, 11);
            jTable2.setValueAt(arr1.get(i).getDivision(), i, 12);

        }
    }//GEN-LAST:event_ResetActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();

        List<Alumnos> arr1 = lista_alumnos.buscadorFiltro("1ro");

        
        for (int i = 0; i < arr1.size(); i++) {
            
                modelo.addRow(o);
                jTable2.setValueAt(arr1.get(i).getMarca_Temporal(), i, 0);
                jTable2.setValueAt(arr1.get(i).getDNI(), i, 1);
                jTable2.setValueAt(arr1.get(i).getApellido(), i, 2);
                jTable2.setValueAt(arr1.get(i).getNombre(), i, 3);
                jTable2.setValueAt(arr1.get(i).getFecha_N(), i, 4);
                jTable2.setValueAt(arr1.get(i).getEdad(), i, 5);
                jTable2.setValueAt(arr1.get(i).getDireccion(), i, 6);
                jTable2.setValueAt(arr1.get(i).getPiso_Depto(), i, 7);
                jTable2.setValueAt(arr1.get(i).getLocalidad(), i, 8);
                jTable2.setValueAt(arr1.get(i).getCorreo(), i, 9);
                jTable2.setValueAt(arr1.get(i).getCelular(), i, 10);
                jTable2.setValueAt(arr1.get(i).getCurso(), i, 11);
                jTable2.setValueAt(arr1.get(i).getDivision(), i, 12);
            
           
        }

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();

        List<Alumnos> arr1 = lista_alumnos.buscadorFiltro("4to");

        
        for (int i = 0; i < arr1.size(); i++) {
            
                modelo.addRow(o);
                jTable2.setValueAt(arr1.get(i).getMarca_Temporal(), i, 0);
                jTable2.setValueAt(arr1.get(i).getDNI(), i, 1);
                jTable2.setValueAt(arr1.get(i).getApellido(), i, 2);
                jTable2.setValueAt(arr1.get(i).getNombre(), i, 3);
                jTable2.setValueAt(arr1.get(i).getFecha_N(), i, 4);
                jTable2.setValueAt(arr1.get(i).getEdad(), i, 5);
                jTable2.setValueAt(arr1.get(i).getDireccion(), i, 6);
                jTable2.setValueAt(arr1.get(i).getPiso_Depto(), i, 7);
                jTable2.setValueAt(arr1.get(i).getLocalidad(), i, 8);
                jTable2.setValueAt(arr1.get(i).getCorreo(), i, 9);
                jTable2.setValueAt(arr1.get(i).getCelular(), i, 10);
                jTable2.setValueAt(arr1.get(i).getCurso(), i, 11);
                jTable2.setValueAt(arr1.get(i).getDivision(), i, 12);
            
           
        }
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();

        List<Alumnos> arr1 = lista_alumnos.buscadorFiltro("3ro");

        
        for (int i = 0; i < arr1.size(); i++) {
            
                modelo.addRow(o);
                jTable2.setValueAt(arr1.get(i).getMarca_Temporal(), i, 0);
                jTable2.setValueAt(arr1.get(i).getDNI(), i, 1);
                jTable2.setValueAt(arr1.get(i).getApellido(), i, 2);
                jTable2.setValueAt(arr1.get(i).getNombre(), i, 3);
                jTable2.setValueAt(arr1.get(i).getFecha_N(), i, 4);
                jTable2.setValueAt(arr1.get(i).getEdad(), i, 5);
                jTable2.setValueAt(arr1.get(i).getDireccion(), i, 6);
                jTable2.setValueAt(arr1.get(i).getPiso_Depto(), i, 7);
                jTable2.setValueAt(arr1.get(i).getLocalidad(), i, 8);
                jTable2.setValueAt(arr1.get(i).getCorreo(), i, 9);
                jTable2.setValueAt(arr1.get(i).getCelular(), i, 10);
                jTable2.setValueAt(arr1.get(i).getCurso(), i, 11);
                jTable2.setValueAt(arr1.get(i).getDivision(), i, 12);
            
           
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();
        for (int i = 0; i < arr1.size(); i++) {
            modelo.addRow(o);
            jTable2.setValueAt(arr1.get(i).getMarca_Temporal(), i, 0);
            jTable2.setValueAt(arr1.get(i).getDNI(), i, 1);
            jTable2.setValueAt(arr1.get(i).getApellido(), i, 2);
            jTable2.setValueAt(arr1.get(i).getNombre(), i, 3);
            jTable2.setValueAt(arr1.get(i).getFecha_N(), i, 4);
            jTable2.setValueAt(arr1.get(i).getEdad(), i, 5);
            jTable2.setValueAt(arr1.get(i).getDireccion(), i, 6);
            jTable2.setValueAt(arr1.get(i).getPiso_Depto(), i, 7);
            jTable2.setValueAt(arr1.get(i).getLocalidad(), i, 8);
            jTable2.setValueAt(arr1.get(i).getCorreo(), i, 9);
            jTable2.setValueAt(arr1.get(i).getCelular(), i, 10);
            jTable2.setValueAt(arr1.get(i).getCurso(), i, 11);
            jTable2.setValueAt(arr1.get(i).getDivision(), i, 12);

        }


    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();

        List<Alumnos> arr1 = lista_alumnos.buscadorFiltro("6to");

        
        for (int i = 0; i < arr1.size(); i++) {
            
                modelo.addRow(o);
                jTable2.setValueAt(arr1.get(i).getMarca_Temporal(), i, 0);
                jTable2.setValueAt(arr1.get(i).getDNI(), i, 1);
                jTable2.setValueAt(arr1.get(i).getApellido(), i, 2);
                jTable2.setValueAt(arr1.get(i).getNombre(), i, 3);
                jTable2.setValueAt(arr1.get(i).getFecha_N(), i, 4);
                jTable2.setValueAt(arr1.get(i).getEdad(), i, 5);
                jTable2.setValueAt(arr1.get(i).getDireccion(), i, 6);
                jTable2.setValueAt(arr1.get(i).getPiso_Depto(), i, 7);
                jTable2.setValueAt(arr1.get(i).getLocalidad(), i, 8);
                jTable2.setValueAt(arr1.get(i).getCorreo(), i, 9);
                jTable2.setValueAt(arr1.get(i).getCelular(), i, 10);
                jTable2.setValueAt(arr1.get(i).getCurso(), i, 11);
                jTable2.setValueAt(arr1.get(i).getDivision(), i, 12);
            
           
        }
        
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();

        List<Alumnos> arr1 = lista_alumnos.buscadorFiltro("2do");

        
        for (int i = 0; i < arr1.size(); i++) {
            
                modelo.addRow(o);
                jTable2.setValueAt(arr1.get(i).getMarca_Temporal(), i, 0);
                jTable2.setValueAt(arr1.get(i).getDNI(), i, 1);
                jTable2.setValueAt(arr1.get(i).getApellido(), i, 2);
                jTable2.setValueAt(arr1.get(i).getNombre(), i, 3);
                jTable2.setValueAt(arr1.get(i).getFecha_N(), i, 4);
                jTable2.setValueAt(arr1.get(i).getEdad(), i, 5);
                jTable2.setValueAt(arr1.get(i).getDireccion(), i, 6);
                jTable2.setValueAt(arr1.get(i).getPiso_Depto(), i, 7);
                jTable2.setValueAt(arr1.get(i).getLocalidad(), i, 8);
                jTable2.setValueAt(arr1.get(i).getCorreo(), i, 9);
                jTable2.setValueAt(arr1.get(i).getCelular(), i, 10);
                jTable2.setValueAt(arr1.get(i).getCurso(), i, 11);
                jTable2.setValueAt(arr1.get(i).getDivision(), i, 12);
            
           
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();

        List<Alumnos> arr1 = lista_alumnos.buscadorFiltro("5to");

        
        for (int i = 0; i < arr1.size(); i++) {
            
                modelo.addRow(o);
                jTable2.setValueAt(arr1.get(i).getMarca_Temporal(), i, 0);
                jTable2.setValueAt(arr1.get(i).getDNI(), i, 1);
                jTable2.setValueAt(arr1.get(i).getApellido(), i, 2);
                jTable2.setValueAt(arr1.get(i).getNombre(), i, 3);
                jTable2.setValueAt(arr1.get(i).getFecha_N(), i, 4);
                jTable2.setValueAt(arr1.get(i).getEdad(), i, 5);
                jTable2.setValueAt(arr1.get(i).getDireccion(), i, 6);
                jTable2.setValueAt(arr1.get(i).getPiso_Depto(), i, 7);
                jTable2.setValueAt(arr1.get(i).getLocalidad(), i, 8);
                jTable2.setValueAt(arr1.get(i).getCorreo(), i, 9);
                jTable2.setValueAt(arr1.get(i).getCelular(), i, 10);
                jTable2.setValueAt(arr1.get(i).getCurso(), i, 11);
                jTable2.setValueAt(arr1.get(i).getDivision(), i, 12);
            
           
        }
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        this.setVisible(false);
        FPrincipal f=new FPrincipal();
        f.show();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);
        FvisualizacionBD f=new FvisualizacionBD();
        f.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        this.setVisible(false);
        FInsertarAlumno is = new FInsertarAlumno();
        is.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setVisible(false);
        FActualizarAlumnos f=new FActualizarAlumnos();
        f.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.setVisible(false);
        FEliminarAlumno f=new FEliminarAlumno();
        f.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.setVisible(false);
        FvisualizacionPadres f=new FvisualizacionPadres();
        f.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        this.setVisible(false);
        FInsertarPadre f=new FInsertarPadre();
        f.show();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.setVisible(false);
        FActualizarPadres f=new FActualizarPadres();
        f.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        this.setVisible(false);
        FElliminarPadre f=new FElliminarPadre();
        f.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        this.setVisible(false);
        FAcercaDe f=new FAcercaDe();
        f.show();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        this.setVisible(false);
        FManualUsuario f=new FManualUsuario();
        f.show();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        if (evt.getKeyChar() != evt.VK_BACK_SPACE) {
            jTextField1.setText(jTextField1.getText() + evt.getKeyChar());
            evt.consume();
        } 
        
        String a = jTextField1.getText();
        
        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();

        List<Alumnos> arr1 = lista_alumnos.buscadorLike(a);

        for (int i = 0; i < arr1.size(); i++) {
            System.out.println(arr1.get(i).getApellido());
        }

        for (int i = 0; i < arr1.size(); i++) {
            modelo.addRow(o);
            jTable2.setValueAt(arr1.get(i).getMarca_Temporal(), i, 0);
            jTable2.setValueAt(arr1.get(i).getDNI(), i, 1);
            jTable2.setValueAt(arr1.get(i).getApellido(), i, 2);
            jTable2.setValueAt(arr1.get(i).getNombre(), i, 3);
            jTable2.setValueAt(arr1.get(i).getFecha_N(), i, 4);
            jTable2.setValueAt(arr1.get(i).getEdad(), i, 5);
            jTable2.setValueAt(arr1.get(i).getDireccion(), i, 6);
            jTable2.setValueAt(arr1.get(i).getPiso_Depto(), i, 7);
            jTable2.setValueAt(arr1.get(i).getLocalidad(), i, 8);
            jTable2.setValueAt(arr1.get(i).getCorreo(), i, 9);
            jTable2.setValueAt(arr1.get(i).getCelular(), i, 10);
            jTable2.setValueAt(arr1.get(i).getCurso(), i, 11);
            jTable2.setValueAt(arr1.get(i).getDivision(), i, 12);
            
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.ButtonGroup filtroAños;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}

